### ISSUE TITLE
Error when reloading with scriptwatcher

### ISSUE THREAD

**Issue by MCrafterzz** [ranjian0/building_tool#118]
I'm not totally sure if it's due to scriptwatcher or this so if it's a scriptwatcher problem then I'll recreate the issue there.

**Describe the bug**
Can't reload script after error, without restarting blender.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start watching the script
2. See the Building Tools tab appear
3. Edit the code so there is an error
4. Tab disappears
5. Fix the error, save and reload the script
6. You get the current error:
[Script Watcher]: There was an error when loading the module:
Traceback (most recent call last):
  File "C:\Users\marcu\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\script_watcher.py", line 151, in load_module
    exec(compile(f.read(), self.filepath, 'exec'), mod.__dict__)
  File "C:\Users\marcu\Documents\Github\building_tool\__init__.py", line 127, in <module>
    register()
  File "C:\Users\marcu\Documents\Github\building_tool\__init__.py", line 107, in register
    register_core()
  File "C:\Users\marcu\Documents\Github\building_tool\core\register.py", line 46, in register_core
    func()
  File "C:\Users\marcu\Documents\Github\building_tool\core\generic.py", line 262, in register_generic
    bpy.utils.register_class(cls)
ValueError: register_class(...): already registered as a subclass 'ArchProperty'

So it seams like the classes aren't unregistered correctly so it tried to register already registered classes. Maybe there's a way to see if it's already registered? And in that case unregister it first.

**Expected behaviour**
The tool starting to work again after the error is fixed

**Comment by MCrafterzz** [comment]
After some more testing this seams to happen after any script change

**Comment by MCrafterzz** [comment]
After some more testing this seams to happen after changing any script in the building tools folder, regarless if it creates an error or not
