### ISSUE TITLE
Multigroup Crash when adjusting size

### ISSUE THREAD

**Issue by ranjian0** [ranjian0/building_tool#45]
```python
Traceback (most recent call last):
  File "/media/ranjian0/Backup/Workspace/projects/building_tool/core/multigroup/multigroup_ops.py", line 22, in execute
    return Multigroup.build(self.props)
  File "/media/ranjian0/Backup/Workspace/projects/building_tool/core/multigroup/multigroup.py", line 16, in build
    if create_multigroup(bm, faces, props):
  File "/media/ranjian0/Backup/Workspace/projects/building_tool/core/multigroup/multigroup_types.py", line 46, in create_multigroup
    doors, windows, arch = create_multigroup_frame(bm, face, prop)
  File "/media/ranjian0/Backup/Workspace/projects/building_tool/core/multigroup/multigroup_types.py", line 78, in create_multigroup_frame
    door_faces, window_faces, frame_faces = make_multigroup_insets(bm, face, prop.size_offset.size, prop.frame_thickness, dws)
  File "/media/ranjian0/Backup/Workspace/projects/building_tool/core/multigroup/multigroup_types.py", line 157, in make_multigroup_insets
    ws, fs = make_window_insets(bm, f, dw['count'], window_height, dw_width, frame_thickness, i==0, i==len(dws)-1)
  File "/media/ranjian0/Backup/Workspace/projects/building_tool/core/multigroup/multigroup_types.py", line 183, in make_window_insets
    face = subdivide_face_vertically(bm, face, [face_height - (window_height+2*frame_thickness), window_height+2*frame_thickness])[1]
IndexError: list index out of range

location: <unknown location>:-1

location: <unknown location>:-1
Error: Traceback (most recent call last):
  File "/media/ranjian0/Backup/Workspace/projects/building_tool/core/multigroup/multigroup_ops.py", line 22, in execute
    return Multigroup.build(self.props)
  File "/media/ranjian0/Backup/Workspace/projects/building_tool/core/multigroup/multigroup.py", line 16, in build
    if create_multigroup(bm, faces, props):
  File "/media/ranjian0/Backup/Workspace/projects/building_tool/core/multigroup/multigroup_types.py", line 46, in create_multigroup
    doors, windows, arch = create_multigroup_frame(bm, face, prop)
  File "/media/ranjian0/Backup/Workspace/projects/building_tool/core/multigroup/multigroup_types.py", line 78, in create_multigroup_frame
    door_faces, window_faces, frame_faces = make_multigroup_insets(bm, face, prop.size_offset.size, prop.frame_thickness, dws)
  File "/media/ranjian0/Backup/Workspace/projects/building_tool/core/multigroup/multigroup_types.py", line 157, in make_multigroup_insets
    ws, fs = make_window_insets(bm, f, dw['count'], window_height, dw_width, frame_thickness, i==0, i==len(dws)-1)
  File "/media/ranjian0/Backup/Workspace/projects/building_tool/core/multigroup/multigroup_types.py", line 183, in make_window_insets
    face = subdivide_face_vertically(bm, face, [face_height - (window_height+2*frame_thickness), window_height+2*frame_thickness])[1]
IndexError: list index out of range

location: <unknown location>:-1
```

Adjusting(minimizing) the size of a multigroup element crashes blender with the above message.

**Comment by luckykadam** [comment]
@ranjian0 assign this to me
