### ISSUE TITLE
Multigroup Crashes

### ISSUE THREAD

**Issue by ranjian0** [ranjian0/building_tool#59]
- [ ] Crash 1. Occurs when I add an arch and adjust the arch height too low.
```python
location: <unknown location>:-1
Error: Traceback (most recent call last):
  File "/media/ranjian0/Backup/Workspace/projects/building_tool/core/multigroup/multigroup_ops.py", line 22, in execute
    return Multigroup.build(self.props)
  File "/media/ranjian0/Backup/Workspace/projects/building_tool/core/multigroup/multigroup.py", line 16, in build
    if create_multigroup(bm, faces, props):
  File "/media/ranjian0/Backup/Workspace/projects/building_tool/core/multigroup/multigroup_types.py", line 46, in create_multigroup
    doors, windows, arch = create_multigroup_frame(bm, face, prop)
  File "/media/ranjian0/Backup/Workspace/projects/building_tool/core/multigroup/multigroup_types.py", line 109, in create_multigroup_frame
    add_faces_to_map(bm, frame_faces, FaceMap.FRAME)
  File "/media/ranjian0/Backup/Workspace/projects/building_tool/utils/util_material.py", line 89, in add_faces_to_map
    face[face_map] = group_index
ReferenceError: BMesh data of type BMFace has been removed

location: <unknown location>:-1
```

- [x] Crash 2. Occurs when I set frame thickness to 0.

```python
Error: Traceback (most recent call last):
  File "/media/ranjian0/Backup/Workspace/projects/building_tool/core/multigroup/multigroup_ops.py", line 22, in execute
    return Multigroup.build(self.props)
  File "/media/ranjian0/Backup/Workspace/projects/building_tool/core/multigroup/multigroup.py", line 16, in build
    if create_multigroup(bm, faces, props):
  File "/media/ranjian0/Backup/Workspace/projects/building_tool/core/multigroup/multigroup_types.py", line 46, in create_multigroup
    doors, windows, arch = create_multigroup_frame(bm, face, prop)
  File "/media/ranjian0/Backup/Workspace/projects/building_tool/core/multigroup/multigroup_types.py", line 78, in create_multigroup_frame
    door_faces, window_faces, frame_faces = make_multigroup_insets(bm, face, prop.size_offset.size, prop.frame_thickness, dws)
  File "/media/ranjian0/Backup/Workspace/projects/building_tool/core/multigroup/multigroup_types.py", line 162, in make_multigroup_insets
    dw_count = count(components)
NameError: name 'components' is not defined

location: <unknown location>:-1
```

**Comment by luckykadam** [comment]
Crash 2 should never happen after #83 
And I cant reproduce crash 1 after #83 

@ranjian0 can you if crash 1 is reproducible. If no then lets close this issue.

**Comment by ranjian0** [comment]
Yep, can't reproduce either after #83.
