### ISSUE TITLE
Roof: Crash when adding roof (hip)

### ISSUE THREAD

**Issue by luckykadam** [ranjian0/building_tool#81]
Blender crashes when adding roof (hip type) on polygon. The flat type roof works fine on the same polygon.

stack trace:
```
location: <unknown location>:-1
Error: Traceback (most recent call last):
  File "/Users/lucky.kadam/Library/Application Support/Blender/2.82/scripts/addons/building_tool/core/roof/roof_ops.py", line 20, in execute
    return Roof.build(context, self.props)
  File "/Users/lucky.kadam/Library/Application Support/Blender/2.82/scripts/addons/building_tool/core/roof/roof.py", line 16, in build
    create_roof(bm, faces, props)
  File "/Users/lucky.kadam/Library/Application Support/Blender/2.82/scripts/addons/building_tool/core/roof/roof_types.py", line 32, in create_roof
    create_hip_roof(bm, faces, prop)
  File "/Users/lucky.kadam/Library/Application Support/Blender/2.82/scripts/addons/building_tool/core/roof/roof_types.py", line 120, in create_hip_roof
    skeleton = skeletonize(points, [])
  File "/Users/lucky.kadam/Library/Application Support/Blender/2.82/scripts/addons/building_tool/utils/util_skeleton.py", line 896, in skeletonize
    i = prioque.get()
  File "/Users/lucky.kadam/Library/Application Support/Blender/2.82/scripts/addons/building_tool/utils/util_skeleton.py", line 863, in get
    return heapq.heappop(self.__data)
TypeError: '<' not supported between instances of 'LineSegment2' and 'LAVertex'
```

<img width="860" alt="Screenshot 2020-04-25 at 5 05 13 PM" src="https://user-images.githubusercontent.com/11018027/80278845-2ac87800-8717-11ea-93b7-0961b3aad14e.png">

**Comment by ranjian0** [comment]
@luckykadam  Can you send me a blend file for that.

**Comment by luckykadam** [comment]
PFA: file with the issue


Lucky Kadam,
+91 8376088574

**Comment by ranjian0** [comment]
No attachment??

**Comment by luckykadam** [comment]
@ranjian0  I have mailed you the file separately.

**Comment by ranjian0** [comment]
Received. Still trying to get to the bottom of this.
